spring:
  mvc:
    format:
      date: dd-MM-yyyy
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/CNExpenses?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate.globally_quoted_identifiers: true
    hibernate.connection: autocommit


server:
  port: 8082